CREATE OR ALTER VIEW Analytics.[Stock Item]
AS
SELECT StockItemKey,
       StockCode AS [Stock Code],
       StockItemDescription AS [Stock Item Description],
       Size,
       SellingPackage AS [Selling Package],
       WeightPerUnit AS [Weight Per Unit],
       StockCategory AS [Stock Category],
       BarCode AS [Bar Code],
       TaxRate AS [Tax Rate],
       IsStocktakeItem AS [Is Stocktake Item],
       UnitPrice AS [Unit Price],
       OuterPrice AS [Outer Price],
       WholesalePrice AS [Wholesale Price],
       AgentPrice AS [Agent Price],
       RecommendedRetailPrice AS [Recommended Retail Price],
       PromotionalPrice AS [Promotional Price],
       PromotionStartDate AS [Promotion Start Date],
       PromotionEndDate AS [Promotion End Date],
       QuantityPerShipper AS [Quantity per Shipper],
       QuantityPerCarton AS [Quantity per Carton],
       QuantityPerPallet AS [Quantity per Pallet],
       IsShownOnPriceList AS [Is Shown on Price List],
       AddedDate AS [Added Date],
       LastPriceChangeDateTime AS [Last Price Change Date Time],
       Brand AS [Brand],
       OrderingPackage AS [Ordering Package],
       QuantityOnHand AS [Quantity on Hand],
       QuantityAtLastStocktake AS [Quantity at Last Stocktake],
       ReorderLevel AS [Reorder Level],
       TypicalLeadTimeDays AS [Typical Lead Time Days],
       IsRecentlyActive AS [Is Recently Active],
       LatestCostPrice AS [Latest Cost Price],
       Comments,
       PrimarySupplierKey,
       AlternateSupplierKey,
       PrimarySupplierStockCode AS [Primary Supplier Stock Code],
       AlternateSupplierStockCode AS [Alternate Supplier Stock Code]
FROM DataModel.StockItems;
GO
